@startuml
skinparam style strictuml
hide footbox
scale max 800 width
skinparam backgroundColor white


title UML-Sequenzdiagramm Fahrplanermittlung

actor Benutzer
participant Main
participant "FahrplanErmittler" as FE
participant "InputHandlerInterface" as IHI
participant "FahrplanStrategie" as FS
participant "OutputHandlerInterface" as OHI

Benutzer -> Main: Programmstart mit inputPath
activate Main
create FE
Main -->> FE: new(inputHandler, outputHandler)

loop für jede Strategie
  Main -> FE: addStrategie(strategie)
end

alt keine Exception
  Main -> FE: ermittleFahrplan(inputPath)
  activate FE
  FE -> IHI: handleInput(path + ".txt")
  activate IHI
  IHI -->> FE: strecken
  deactivate IHI

  loop für jede registrierte Strategie
    FE -> FS: ermittleFahrplan(strecken)
    activate FS
    FS -->> FE: fahrplan
    deactivate FS
  end

  FE -> OHI: createOutput(fahrplaene, strategieNamen, path)
  deactivate FE

else InputHandlerException
  Main -> FE: ermittleFahrplan(inputPath)
  activate FE
  FE -> IHI: handleInput(path + ".txt")
  activate IHI
  IHI -->> FE: InputHandlerException
  deactivate IHI
  FE -->> Main: InputHandlerException
  deactivate FE
  Main -> Main: errors.add(e.getMessage())

else OutputHandlerException
  Main -> FE: ermittleFahrplan(inputPath)
  activate FE
  FE -> IHI: handleInput(path + ".txt")
  activate IHI
  IHI -->> FE: strecken
  deactivate IHI

  loop fuer jede registrierte Strategie
    FE -> FS: ermittleFahrplan(strecken)
    activate FS
    FS -->> FE: fahrplan
    deactivate FS
  end

  FE -> OHI: createOutput(fahrplaene, strategieNamen, path)
  activate OHI
  OHI -->> FE: OutputHandlerException
  deactivate OHI
  FE -->> Main: OutputHandlerException
  deactivate FE
  Main -> Main: errors.add(e.getMessage())
end

opt errors nicht leer
  loop für jede Fehlermeldung
    Main -> Main: System.out.println(error)
  end
end

deactivate Main
@enduml

